import { ThemeProvider } from "@/providers/ThemeProvider";
import "../globals.css";
import { TanstackProvider } from "@/providers/TanstackProvider";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <TanstackProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
