import { ThemeProvider } from "@/providers/ThemeProvider";
import "../globals.css";
import { TanstackProvider } from "@/providers/TanstackProvider";
import { Toaster } from "sonner";
export const metadata = {
  title: "eGARC Client",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="w-full h-svh bg-white dark:bg-background">
        <TanstackProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <main className="flex w-full h-full">{children}</main>
          </ThemeProvider>
        </TanstackProvider>
        <Toaster />
      </body>
    </html>
  );
}
