import "../../globals.css";

export const metadata = {
  title: "eGARC Client",
  description: "Generated by Next.js",
};

export default function SettingsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
