import "@/app/globals.css";
export const metadata = {
  title: "eGARC Client",
  description: "Generated by Next.js",
};

export default function EngagementLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="w-[100vw] h-[100vh]">
      <main className="flex-1 flex h-full">{children}</main>
    </section>
  );
}
