import "@/app/globals.css";
export const metadata = {
  title: "eGARC Client",
  description: "Generated by Next.js",
};

export default function EngagementLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="flex flex-col w-full">
      <main className="flex-1 flex h-full">{children}</main>
    </section>
  );
}
