import "@/app/globals.css";
import { EngagementSidebarMenu } from "@/components/menus/engagement-sidebar-menu";
import { Separator } from "@/components/ui/separator";
import { EauditNavbar } from "@/components/top-navbars/eaudit-navbar";
import { BreadCrumbNavbar } from "@/components/shared/breadcrum-nav";
import BreadcrumbTracker from "@/components/shared/breadcrumb-tracker";

export const metadata = {
  title: "eGARC Client",
  description: "Generated by Next.js",
};

export default function EngagementLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="flex flex-col w-[100vw] h-[100vh]">
        <header className="py-2 pl-1 flex flex-col gap-4">
          <EauditNavbar />
          <section className="px-4">
            <BreadCrumbNavbar />
          </section>
        </header>
        <Separator className="mt-4 bg-neutral-500" />
        <main className="flex-1 flex">
          <section className="w-[320px] px-1 pt-2">
            <EngagementSidebarMenu />
          </section>
          <Separator orientation="vertical" className="bg-neutral-500 ml-1" />
          <section className="flex-1 flex h-[100vh]">{children}</section>
        </main>
      </div>
      <BreadcrumbTracker />
    </>
  );
}
