import { EngagementNavbar } from "@/components/top-navbars/engagement-navbar";
import "@/app/globals.css";
import { EngagementSidebarMenu } from "@/components/menus/engagement-sidebar-menu";
import { Separator } from "@/components/ui/separator";

export const metadata = {
  title: "eGARC Client",
  description: "Generated by Next.js",
};

export default function EngagementLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="flex flex-col w-full">
      <header className="py-2 pl-1">
        <EngagementNavbar />
      </header>
      <Separator />
      <main className="flex-1 flex h-full">
        <section className="w-[320px] h-full px-1 pt-1">
          <EngagementSidebarMenu />
        </section>
        <Separator orientation="vertical" />
        <section className="flex-1 flex">{children}</section>
      </main>
    </section>
  );
}
