import { PreferencesNavbar } from "@/components/top-navbars/preferences-navbar";
import "@/app/globals.css";
import { Separator } from "@/components/ui/separator";

export const metadata = {
  title: "eGARC Client",
  description: "Generated by Next.js",
};

export default function PreferencesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="flex flex-col w-full">
      <header className="py-2 pl-1">
        <PreferencesNavbar />
      </header>
      <Separator />
      <main className="flex-1 flex h-full">
        <section className="flex-1 flex">{children}</section>
      </main>
    </section>
  );
}
